path: data/v1/
train: images/train
val: images/valid
nc: 16
names: [kfc, fanta, pepsi, danone, adidas, mcdonald, zara, chanel, starbucks, sprite,
  7up, carrefour, hp, dominos-pizza, kitkat, papajohns]
hyp:
  lr0: 0.01           # Initial learning rate
  batch_size: 2      # Adjust based on GPU memory and dataset size
  optimizer: SGD      # Experiment with Adam or RMSprop if needed
